version: '3.8'

services:
  logging_api:
    depends_on:
      - redis
      - postgres
    image: ${IMG_URL}
    command: ["python3", "search_benchmark/ranking/logging_api.py"]
    deploy: 
      mode: replicated
      replicas: 10
    env_file:
      - path: .env
        required: false 
    environment:
      - PG_REDIS_URL=redis://redis:6379
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - SEMANTIC_SCHOLAR_API_KEY=${SEMANTIC_SCHOLAR_API_KEY}
      - API_URL=${API_URL}
  
  questions:
    depends_on:
      - redis
      - postgres
    image: ${IMG_URL}
    command: ["python3", "search_benchmark/search/questions.py"]
    deploy: 
      mode: replicated
      replicas: 0
    env_file:
      - path: .env
        required: false 
    environment:
      - PG_REDIS_URL=redis://redis:6379
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - SEMANTIC_SCHOLAR_API_KEY=${SEMANTIC_SCHOLAR_API_KEY}
      - API_URL=${API_URL}
  
  responses:
    depends_on:
      - redis
      - postgres
    image: ${IMG_URL}
    command: ["python3", "search_benchmark/search/responses.py"]
    deploy: 
      mode: replicated
      replicas: 50
    env_file:
      - path: .env
        required: false 
    environment:
      - PG_REDIS_URL=redis://redis:6379
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - SEMANTIC_SCHOLAR_API_KEY=${SEMANTIC_SCHOLAR_API_KEY}
      - API_URL=${API_URL}
  
  ranking:
    depends_on:
      - redis
      - postgres
    image: ${IMG_URL}
    command: ["python3", "search_benchmark/ranking/ranking.py"]
    deploy: 
      mode: replicated
      replicas: 50
    env_file:
      - path: .env
        required: false 
    environment:
      - PG_REDIS_URL=redis://redis:6379
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - SEMANTIC_SCHOLAR_API_KEY=${SEMANTIC_SCHOLAR_API_KEY}
      - API_URL=${API_URL}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  redis_data:
  postgres_data: